from __future__ import annotations

import argparse
from pathlib import Path

from app.config import CHUNK_OVERLAP, CHUNK_SIZE
from app.ingestion.chunker import chunk_documents
from app.ingestion.loader import load_documents
from app.llm.generator import generate_answer
from app.llm.prompts import REFUSAL, build_rag_prompt
from app.retrieval.retriever import retrieve_relevant_chunks


QUESTIONS = [
    {"id": "Q1", "question": "What are the four execution states of a .NET MAUI app?", "source": "app-lifecycle.md", "section": "App lifecycle"},
    {"id": "Q2", "question": "Which cross-platform lifecycle event is raised when a window is no longer visible?", "source": "app-lifecycle.md", "section": "Cross-platform lifecycle events"},
    {"id": "Q3", "question": "Where are dependencies registered in a .NET MAUI application?", "source": "dependency-injection.md", "section": "Registration"},
    {"id": "Q4", "question": "What is the difference between AddSingleton and AddTransient?", "source": "dependency-injection.md", "section": "Dependency lifetime"},
    {"id": "Q5", "question": "What is the default number of rows and columns in a .NET MAUI Grid?", "source": "grid.md", "section": "Rows and columns"},
    {"id": "Q6", "question": "What are the three GridUnitType values used for row heights and column widths?", "source": "grid.md", "section": "Rows and columns"},
    {"id": "Q7", "question": "What are the main parts of a XAML file described in the getting-started documentation?", "source": "fundamentals-get-started.md", "section": "Anatomy of a XAML file"},
    {"id": "Q8", "question": "How can XAML interact with code in a .NET MAUI application?", "source": "fundamentals-get-started.md", "section": "XAML and code interactions"},
]

REFUSAL_QUESTIONS = [
    "What is the maximum number of concurrent requests supported by the undocumented SDK endpoint?",
    "What is the retry_backoff_ms default for an API that does not appear in these documents?",
    "What is the pricing of the SDK API described in these documents?",
]

def hit(question: dict, results: list[dict]) -> bool:
    source = question["source"].lower()
    section = question["section"].lower()
    return any(
        str(r.get("source_file", "")).lower() == source
        and section in str(r.get("section", "")).lower()
        for r in results[:5]
    )


def citation_is_valid(citation, docs) -> bool:
    for doc in docs:
        if (
            citation.chunk_id == doc.get("chunk_id")
            and citation.source_file == doc.get("source_file")
            and citation.page_id == doc.get("page_id")
            and citation.section == doc.get("section", "")
        ):
            return True
    return False


def write_results(path: Path, search_records: dict, generated: list[tuple[str, str, object]], refusals: list[tuple[str, object]], metadata_note: str) -> None:
    lines = [
        "# Week 3 — Developer Documentation RAG Results",
        "",
        "> Generated by `evaluate_rag.py`. Search questions were written from known documentation sections before retrieval was run.",
        "",
        "## 1. Known-answer questions",
        "",
        "| ID | Question | Expected page | Expected section |",
        "|---|---|---|---|",
    ]
    for q in QUESTIONS:
        lines.append(f"| {q['id']} | {q['question']} | `{q['source']}` | {q['section']} |")

    lines += ["", "## 2. Hit@5 comparison", "", "| Strategy | Hit@5 |", "|---|---:|"]
    for strategy in ("baseline", "structure"):
        records = search_records[strategy]
        score = sum(1 for q in QUESTIONS if records[q["id"]]["hit"])
        lines.append(f"| {strategy} | {score}/8 |")

    lines += ["", "### Per-question record", "", "| ID | Baseline | Structure-aware |", "|---|---|---|"]
    for q in QUESTIONS:
        b = search_records["baseline"][q["id"]]
        s = search_records["structure"][q["id"]]
        lines.append(f"| {q['id']} | {'HIT' if b['hit'] else 'MISS'} | {'HIT' if s['hit'] else 'MISS'} |")

    lines += ["", "## 3. Unfiltered vs metadata-filtered retrieval", "", metadata_note, ""]

    lines += ["## 4. Three grounded answers", ""]
    for q, answer, result in generated:
        lines += [f"### {q}", "", answer, "", "Citations:"]
        for c in result.citations:
            lines.append(f"- `{c.chunk_id}` — `{c.source_file}` — `{c.section}`")
        lines.append("")

    lines += ["## 5. Three refusal transcripts", ""]
    for q, result in refusals:
        lines += [f"### Question", "", q, "", "### Response", "", result.answer, "", f"grounded: `{result.grounded}`", "", f"citations: `{len(result.citations)}`", ""]

    lines += [
        "## 6. Chunking decision",
        "",
        "The structure-aware chunker is the recommended strategy because it preserves Markdown headings, keeps tables together, and never cuts fenced code blocks across chunks. The baseline remains available so the retrieval difference can be measured on the same questions.",
        "",
        "## 7. Reproducibility",
        "",
        f"Chunk size: `{CHUNK_SIZE}` characters; overlap: `{CHUNK_OVERLAP}` characters. Only the documentation in the local `documents/` directory is indexed by this script.",
        "",
        "The six-page v3 assignment experiment requires the six supplied v3 reference pages. This project does not fabricate v2/v3 data when those pages are absent; once they are placed in the corpus with their correct metadata, rerun the evaluator to populate the version-filter experiment.",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--generation", action="store_true", help="Also run 3 grounded and 3 refusal generation tests.")
    args = parser.parse_args()

    docs = load_documents()
    search_records: dict[str, dict] = {"baseline": {}, "structure": {}}
    dump: list[str] = []

    for strategy in ("baseline", "structure"):
        for q in QUESTIONS:
            results = retrieve_relevant_chunks(q["question"], n_results=5, strategy=strategy)
            search_records[strategy][q["id"]] = {"hit": hit(q, results), "results": results}
            dump.append(f"\n===== {strategy.upper()} / {q['id']} =====\n{q['question']}\n")
            for rank, r in enumerate(results, 1):
                dump.append(
                    f"{rank}. {r.get('source_file')} | {r.get('section')} | "
                    f"score={r.get('score', 0):.4f} | distance={r.get('distance', 0):.4f} | "
                    f"chunk={r.get('chunk_id')}\n"
                )

    Path("search_dump.txt").write_text("".join(dump), encoding="utf-8")

    metadata_note = (
        "The current local corpus contains a single `sdk_version` value, so a meaningful v2-v3 top-1 change cannot be honestly demonstrated yet. "
        "The application and index schema support the filter; add the supplied v2/v3 pages with their correct versions and rerun to produce the required before/after lists."
    )

    generated = []
    refusals = []
    if args.generation:
        for q in [QUESTIONS[1], QUESTIONS[4], QUESTIONS[6]]:
            docs_for_answer = retrieve_relevant_chunks(q["question"], n_results=5, strategy="structure")
            result = generate_answer(build_rag_prompt(q["question"], docs_for_answer))
            invalid = [c for c in result.citations if not citation_is_valid(c, docs_for_answer)]
            if invalid:
                raise RuntimeError(f"Invalid citation returned for question: {q['question']}")
            generated.append((q["question"], result.answer, result))

        for q in REFUSAL_QUESTIONS:
            docs_for_answer = retrieve_relevant_chunks(q, n_results=5, strategy="structure")
            result = generate_answer(build_rag_prompt(q, docs_for_answer))
            refusals.append((q, result))

    write_results(Path("results.md"), search_records, generated, refusals, metadata_note)
    print("Wrote results.md and search_dump.txt")


if __name__ == "__main__":
    main()
